---
# tasks file for clickhouse
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_release | lower }}.yml"
    - "empty.yml"
  tags: [always]

- import_tasks: precheck.yml
  tags: [always]

- include_tasks: "{{ item }}"
  with_first_found:
    - "install_{{ ansible_pkg_mgr }}.yml"
    - "empty.yml"
  when: clickhouse_setup == 'package' and (clickhouse_rt_is_installed.rc !=0 or not clickhouse_is_required_version) and clickhouse_remove|bool == False
  tags: [install]

- import_tasks: precheck.yml
  tags: [always]

- import_tasks: config_sys.yml
  when: clickhouse_rt_is_installed.rc == 0 and clickhouse_remove|bool == False
  tags: [config,config_sys]

- meta: flush_handlers

- name: Check clickhouse server is ready
  command: "clickhouse-client -h 127.0.0.1 --port {{ clickhouse_tcp_port }} -q 'select 1'"
  changed_when: False
  retries: "{{ clickhouse_ready_retries }}"
  delay: "{{ clickhouse_ready_delay }}"
  register: clickhouse_rt_ready
  until: clickhouse_rt_ready.rc == 0
  tags: [config,config_sys]

- import_tasks: config_db.yml
  when: clickhouse_rt_is_installed.rc == 0 and clickhouse_remove|bool == False
  tags: [config,config_db]

- import_tasks: config_dict.yml
  when: clickhouse_rt_is_installed.rc == 0 and clickhouse_remove|bool == False
  tags: [config,config_dict]

- include_tasks: "{{ item }}"
  with_first_found:
    - "remove_{{ ansible_pkg_mgr }}.yml"
    - "empty.yml"
  when: clickhouse_setup == 'package' and clickhouse_rt_is_installed.rc == 0 and clickhouse_remove|bool == True
  tags: [remove]
