#Main installation actions
#https://clickhouse.yandex/docs/en/getting_started/index.html#installation

- name: Uninstall by APT | Stop service
  service:
    name: clickhouse-server
    state: stopped
  become: true

- name: Uninstall by APT | Package uninstallation
  apt:
    name: "{{ clickhouse_package | flatten(levels=1) }}"
    state: absent
    purge: yes
  become: true

- name: Uninstall by APT | Repo uninstallation
  apt_repository:
    repo: "{{ clickhouse_repo }}"
    state: absent
  become: true

- name: Uninstall by APT | Apt-key remove repo key
  apt_key:
    keyserver: "{{ clickhouse_repo_keyserver }}"
    id: "{{ clickhouse_repo_key }}"
    state: absent
  become: true

- name: Remove clickhouse config,data and logs
  file:
    dest: "{{ path_absent }}"
    state: absent
  loop:
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"
  loop_control:
    loop_var: path_absent
  become: true
  when: clickhouse_remove_full|bool == True
