#Main installation actions
#https://clickhouse.yandex/docs/en/getting_started/index.html#installation

- name: Uninstall by YUM | Ensure clickhouse package uninstalled
  yum:
    name: "{{ clickhouse_package | product([clickhouse_version]) | map('join', '-') }}"
    state: absent
    autoremove: yes
  become: true

- name: Uninstall by YUM | Ensure clickhouse repo uninstalled
  yum_repository:
    name: clickhouse
    file: clickhouse
    state: absent
  become: true

- name: Uninstall by YUM | Ensure clickhouse key uninstalled
  rpm_key:
    key: "{{ clickhouse_repo_key }}"
    state: absent
  become: true

- name: Remove clickhouse config,data and logs
  file:
    dest: "{{ path_absent }}"
    state: absent
  loop:
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"
  loop_control:
    loop_var: path_absent
  become: true
  when: clickhouse_remove_full|bool == True
